steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/mlops-33/mlops-docker/project-image',
    '-f',
    'train.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/mlops-33/mlops-docker/project-image'
  ]
options:
  logging: CLOUD_LOGGING_ONLY