method: bayes  
metric:
  name: val_accuracy  
  goal: maximize   
parameters:
  lr:
    values: [0.05,0.01]
  hidden:
    values: [8, 16, 32]         
  dropout:
   values: [0.3, 0.5, 0.7]   
       